name: Doxygen Action

on:
  push
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Make Code Badge
      uses: actions/checkout@v3
      id: badge
      with:
        debug: true
        directory: ./
        badge: ./badge.svg
        patterns: '*.cpp'  # Patterns in the format of a '.gitignore' file, separated by pipes.
        ignore: 'node_modules'
