name: Unite Test 

on:
  push: 
    branches:
      - master

jobs:
  ubuntu-build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: bazel test ...
